[package]
name = "docsplay-macros"
version = "0.1.0"
edition = "2021"

[features]
std = []

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
static_assertions = "1.1"
rustversion = "1.0.0"
pretty_assertions = "1.4.0"
thiserror = "1.0.24"
